services:
  hana-portfolio-fe-sit-services:
    container_name: "hana-portfolio-fe-sit-services"
    restart: unless-stopped
    cpus: 1.0
    mem_limit: 256M
    mem_reservation: 128M
    build:
      context: .
      dockerfile: Dockerfile/Dockerfile.hana-portfolio.sit
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    networks:
      - hana-network
networks:
  hana-network:
    name: hana-network
