permissions:
  contents: read

name: "HANA Portfolio [PROD]"

on:
  push:
    branches:
      - master

jobs:
  portfolio:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 26
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Run unit tests
        run: npm run test

      - name: Run coverage
        run: npm run test:coverage

      - name: NPM Build Package
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          CONTAINER_NAME: HANA_PORTFOLIO_[PROD]
          WORKFLOW_URL: https://github.com/Nicklas373/hana-portfolio/actions/workflows/docker-prod-env.yml
          IMAGE_NAME: portfolio_build_image
          STATUS: Build HANA Portfolio NPM Package
          COMMIT_SHA: ${{ github.sha }}
          COMMIT_MSG: ${{ github.event.head_commit.message }}
          COMMIT_AUTHOR: ${{ github.actor }}
          BRANCH: ${{ github.ref_name }}
          ENV: PROD
        run: |
          chmod +x ./module/bash/docker-build-info.sh
            bash ./module/bash/docker-build-info.sh

      - name: Docker Image Build Notification
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          CONTAINER_NAME: HANA_PORTFOLIO_[PROD]
          WORKFLOW_URL: https://github.com/Nicklas373/hana-portfolio/actions/workflows/docker-prod-env.yml
          IMAGE_NAME: portfolio_build_image
          STATUS: Build HANA Portfolio Docker Image
          COMMIT_SHA: ${{ github.sha }}
          COMMIT_MSG: ${{ github.event.head_commit.message }}
          COMMIT_AUTHOR: ${{ github.actor }}
          BRANCH: ${{ github.ref_name }}
          ENV: PROD
        run: |
          chmod +x ./module/bash/docker-build-info.sh
            bash ./module/bash/docker-build-info.sh

      - name: Build HANA Portfolio Docker Image
        run: |
          docker build \
            --build-arg NEXT_PUBLIC_TURNSTILE_SITE_KEY=${{ secrets.NEXT_PUBLIC_TURNSTILE_SITE_KEY }} \
            -t nicklas373/hana-portfolio-services-prod:1.0.4 \
            -f Dockerfile/Dockerfile.hana-portfolio.prod \
            .
          mkdir -p portfolio_image
          docker save -o portfolio_image/portfolio_image.tar nicklas373/hana-portfolio-services-prod:1.0.4

      - name: Load Docker Image Notifications
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          CONTAINER_NAME: HANA_PORTFOLIO_[PROD]
          WORKFLOW_URL: https://github.com/Nicklas373/hana-portfolio/actions/workflows/docker-prod-env.yml
          IMAGE_NAME: portfolio_build_image
          STATUS: Load HANA Portfolio Docker Image
          COMMIT_SHA: ${{ github.sha }}
          COMMIT_MSG: ${{ github.event.head_commit.message }}
          COMMIT_AUTHOR: ${{ github.actor }}
          BRANCH: ${{ github.ref_name }}
          ENV: PROD
        run: |
          chmod +x ./module/bash/docker-build-info.sh
          bash ./module/bash/docker-build-info.sh

      - name: Load Docker Images
        run: docker load -i portfolio_image/portfolio_image.tar

      - name: Push Docker Image Notifications
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          CONTAINER_NAME: HANA_PORTFOLIO_[PROD]
          WORKFLOW_URL: https://github.com/Nicklas373/hana-portfolio/actions/workflows/docker-prod-env.yml
          IMAGE_NAME: portfolio_build_image
          STATUS: Push HANA Portfolio Docker Image
          COMMIT_SHA: ${{ github.sha }}
          COMMIT_MSG: ${{ github.event.head_commit.message }}
          COMMIT_AUTHOR: ${{ github.actor }}
          BRANCH: ${{ github.ref_name }}
          ENV: PROD
        run: |
          chmod +x ./module/bash/docker-build-info.sh
          bash ./module/bash/docker-build-info.sh

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: nicklas373
          password: ${{ secrets.DOCKER_PAT }}

      - name: Push Docker Image to Docker Hub
        run: docker push nicklas373/hana-portfolio-services-prod:1.0.4

      - name: Status Notifications
        if: always()
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          CONTAINER_NAME: HANA_PORTFOLIO_[PROD]
          WORKFLOW_URL: https://github.com/Nicklas373/hana-portfolio/actions/workflows/docker-prod-env.yml
          IMAGE_NAME: portfolio_build_image
          STATUS: "Build ${{ job.status }}"
          COMMIT_SHA: ${{ github.sha }}
          COMMIT_MSG: ${{ github.event.head_commit.message }}
          COMMIT_AUTHOR: ${{ github.actor }}
          BRANCH: ${{ github.ref_name }}
          ENV: PROD
        run: |
          chmod +x ./module/bash/docker-build-info.sh
          bash ./module/bash/docker-build-info.sh
